[package]
name = "pgvector"
version = "0.2.2"
description = "pgvector support for Rust"
repository = "https://github.com/pgvector/pgvector-rust"
license = "MIT OR Apache-2.0"
authors = ["Andrew Kane <andrew@ankane.org>"]
edition = "2018"
readme = "README.md"

[dependencies]
byteorder = "1"
bytes = "1"
postgres = { version = "0.19", optional = true }
diesel = { version = "2", features = ["postgres"], optional = true }
sqlx = { version = ">= 0.5, < 0.8", features = ["postgres"], optional = true }
serde = {version = "1.0.183", features = ["derive"]}

[dev-dependencies]
sqlx = { version = "0", features = ["runtime-async-std-native-tls"] }
async-std = { version = "1", features = ["attributes"] }

[features]
default = ["postgres"]
